# Generated by Django 4.2.16 on 2024-09-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_comment_approver_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='approver_note',
            field=models.CharField(default=None, null=True),
        ),
    ]
