# Generated by Django 4.2.16 on 2024-09-19 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_comment_approver_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='approver_note',
            field=models.CharField(),
        ),
    ]
