# Generated by Django 4.2.16 on 2024-09-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0010_rename_recipe_id_comment_recipe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('GRAM', 'Gram'), ('KILOGRAM', 'Kilogram'), ('TEASPOON', 'Teaspoon'), ('TABLESPOON', 'Tablespoon'), ('OUNCE', 'Ounce'), ('LITRE', 'Litre'), ('MILLILITRE', 'Millilitre'), ('SMALL', 'Small'), ('LARGE', 'Large'), ('MEDIUM', 'Medium')], max_length=200),
        ),
    ]
