# Generated by Django 4.2.16 on 2024-09-19 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0013_alter_comment_approver_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('ing_id', models.AutoField(primary_key=True, serialize=False)),
                ('ing_name', models.CharField()),
                ('category', models.CharField(choices=[('Meat', 'Meat'), ('Vegetable', 'Vegetable'), ('Fish', 'Fish'), ('Other', 'Other')])),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('unit', models.CharField()),
                ('is_allergen', models.BooleanField(default=False)),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipe.recipe')),
            ],
        ),
    ]
