# Generated by Django 4.2.16 on 2024-09-19 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0014_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
