# Generated by Django 4.2.16 on 2024-09-19 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0015_alter_ingredients_quantity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredients',
            new_name='Ingredient',
        ),
    ]
