# Generated by Django 4.2.16 on 2024-09-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0016_rename_ingredients_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('Gram', 'Gram'), ('Kilogram', 'Kilogram'), ('Teaspoon', 'Teaspoon'), ('Tablespoon', 'Tablespoon'), ('Ounce', 'Ounce'), ('Litre', 'Litre'), ('Millilitre', 'Millilitre')]),
        ),
    ]
